name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: builds the 18.06.6 image
      run: |
        ./build.sh 18.06.6
        echo done
